<a href="https://colab.research.google.com/github/impresso/impresso-datalab-notebooks/blob/impresso@bnf/workshop_resources/ws4-embeddings/explore_introduction-to-embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Understanding Embeddings: Representing and Searching Texts and Images with Impresso

> If something doesn't work, we’ll be grateful for your [problem report](https://github.com/impresso/impresso-datalab-notebooks/blob/main/reporting-problems.md).

## What is this notebook about?

This notebook is designed as a **practical introduction to the Impresso embedding ecosystem**.

1.   The **first section** introduces the general idea behind text embeddings and their associated similarity. This serves as a conceptual foundation for the rest of the material.
2.   The **second section** guides users through two fundamental questions: how embeddings can be inspected to better understand their structure, and how similarity functions work in practice. These two exercises help make the abstract notion of vectors tangible, before moving toward more advanced retrieval workflows.
3.   The **third section** focuses on Impresso’s embedding search capabilities. It explains how to perform text retrieval across multiple languages, how to limit searches by language, and how images can also be retrieved via their own embeddings. Users are then shown how to access both text and image embeddings directly from the Impresso platform, as well as how to retrieve the associated media objects.

## What you will learn:
 - Get an intuition about embeddings and their similarity;
 - Embed texts and images;
 - Retrieve embeddings directly from the Impresso database;
 - Search related texts and images within Impresso.

## Useful resources

- [Impresso Python Library](https://impresso.github.io/impresso-py/)
- [Impresso Hugging Face](https://huggingface.co/impresso-project)

# 1. A Short Theory Primer: Embeddings and their Similarity

If you're already familiar with the concept of embeddings and their similarity, feel free to skip this primer and move directly to the hands-on work with Impresso embedding.

## What are embeddings?

Embeddings are high-dimensional vectors that represent objects. Speaking simply, you may also imagine them as long lists with numbers. Each number in a list stands for a point on a particular axis or dimension, and each list is representing an object (e.g., a document).
For instance [1, 3, 2] can be understood as a point in a three-dimensional space, with x=1, y=3, and z=2.

In applications, like impresso-embeddings, such vectors often have many more dimensions, and thus they escape an intuitive understanding (humans are only able to perceive any space with equal or less than 3 dimensions).
In Impresso, those embedding vectors represent texts and images.

## Why are embeddings useful?

Embeddings allow us to efficiently search documents in a large corpus by assessing their semantic similarity. Imagine you have a document and want to find similar ones among a million others.
Using embeddings, we can quickly find the most similar documents, even across different languages, where documents do not share any of the same words.

## How is embedding similarity measured?

Usually, we use the **cosine similarity**. It's based on the dot-product of two vectors and measures the angle between embeddings, which has been empirically proven to be the most robust way to measure such similarity. Let's see how it looks in Python!

In [1]:
import math

# cosine similarity of two vectors
def norm(vector):
    length = math.sqrt(sum(v**2 for v in vector))
    return length

def vector_similarity(vector1, vector2):
    length1, length2 = norm(vector1), norm(vector2)
    dot_product = sum(v1 * v2 for v1, v2 in zip(vector1, vector2))
    return dot_product / (length1 * length2)

Let's calculate the **similarity of two embeddings**:

In [2]:
vector_a = [1, 2, 3]
vector_b = [4, 5, 6]
similarity = vector_similarity(vector_a, vector_b)
similarity

0.9746318461970762

**Maximum similarity** is when the embeddings point in the exact same direction --> -->!

In [3]:
similarity = vector_similarity(vector_a, vector_a)
similarity

1.0

**Minimum similarity** is when the vectors point in the opposite directions <-- -->!

In [4]:
similarity = vector_similarity(vector_a, [-1 * value for value in vector_a])
similarity

-1.0

**Zero similarity** is also an interesting edge case, it is when the vectors are orthogonal to each other |_ !

In [5]:
similarity = vector_similarity([-1, 1], [1, 1])
similarity

0.0

 ***Take-away**: The cosine similarity of two embedding vectors lies between -1 and 1. 1 means that the represented objects are semantically the same, all other values indicate different degrees of similarity. -1 and 0 are mathematically interesting and conceptually clear edge cases but they don't have any real meaning for the similarity of documents, it would just mean that they are dissimilar.*

# 2. Inspecting Impresso Embeddings and Understanding their Structure

## Prerequisites

Run the following cells to install the required package and to connect to the Impresso API.
In case you are working with Google Colab, you may need to restart the kernel. Go to *Runtime* and select *Restart session*.

> For the datathon, this notebook uses the Impresso development environment: you will be asked for a token from https://dev.impresso-project.ch/datalab/token.

In [ ]:
# Impresso Python package

%pip install --upgrade "git+https://github.com/impresso/impresso-py.git@rev-2026-10-08"

In [7]:
# Connecting to the Impresso API (dev environment, for the datathon)

from impresso import connect, OR, AND, DateRange
client = connect(public_api_url="https://dev.impresso-project.ch/public-api/v1")

🎉 You are now connected to the Impresso API!  🎉
🔗 Using API: https://dev.impresso-project.ch/public-api/v1

## Embedding a text

As discussed in the short theory lesson above, embedding a text means using a **neural network** to turn it into a **high-dimensional vector** that allows efficient comparison across languages and beyond surface wording. Let's start by generating such embeddings right away, using the Impresso API!

In [8]:
embedding = client.tools.embed_text(text="Schumann the politician", target="text")
embedding

'gte-768:9gisvV3v1D1eb1M7DmzzPHz727ssV8u9tNGePJSINTsjoCU9PizcvOsYBzyS+ss88Hp6vRbOkz2Omm69ApNTPU3zqD3sMxE9SDrHPT8+tLzUhjQ9jJERPLSVPjyUPca7gr12vTFZxbwiw889WK2RvW1L5r1zC3g9BS6RvdCPGb3VubM8TXh+PSTwQj1lrAe9F1KKPUN/vTxWwK694ONQvJ3PF72yyxG9xaInvUC7m7yLDT48I5I5PLAldbykQkU8gzQnOcgCaz3+C2q9nPpbPStpgryxU4E8aPvyPOIu8jw2pOe9kUMxPceb0D2r7dy85vZFvLGcHbsThxS9tSnSvEe0FzxzkBO7nP03PSZh87yk7Jo9+umRPUR3gLzQ1AU9gXv7O9jA/TzY0ns8oFHkPbRVSbyYj6885vCdPalzwjw9Lki9sYUYPCJYuDxGbsA8j90gvAv6bzw5csc5/CaIvX2UQbx7VLk8A1d1PaXzEbxZEw88X44nvbp0WLsCOzY8NeynvFfaLDu6Glo8xG3IvFWRJT2/xSM93Z4yPatobLzUSeW8pzYQvU6WyTsI/Ss7kY7IuKUaJDwCn4W9UubCvDKvVb3y9f+83nxdvR9rVz09YV49uqcSvdBQSj3RKmk8/7eyu9z7Ar3gCK68wN/6vBkQxb0p73K8E2uQvbG1kr0IjSo934AIvc2iLz3bkHo8/6rZPF8YD73AXTM8XM8hvZONEL3Ltx894vwtOxTwgDlKlwm9G6qGPFnttr1dxry8X52ZPA62uDxkGqG81G51PPFtJz35mSE7DbplPLBCND0OJvk8x+H/vLOSCbuvC/e8LbIivf5bQD0+C8k7BrSkvFOLdT3AMVI7RzLGPBcCqrwGgkC96N2SOwJ0TLqjgBc93SRaPdLK4LyVZii9sZk5Pf8uBD32Yr27EKnWvI4eFTn38eK8uU0IPegZJ70r3d28g9kZvTf5fb36gY69dnSRvS4bTjxxH4M7/siUvE7FL70I1gC8v8NlPNDCpbws0Xu8Zse7va2RnDyg5I49bn3FvbxPBr2wQMA9djH4unwfWju/7LA8MZrkPFdvKz2ATP88lmKfvHDjbLxVBWu9bEvxvGPPhDwbIC+9LnXDuwlpBLskXow8Pc0hPZikFb3z2qm6E8sjvfeVYLynoZI9T37wvGphnrzQ3E69wB2Fvc86HL35zt48HFBYPZ2I+LvJtSU97vvdu5cmu7zlrNu8/DqiPI30ijolPBm9WRG9OxeEEL1MR3S8AnSwvGICBrzzUGY9U2lJPIXQ37wHH408nxIIPT8ECr3e5t28ZGQquz2duzo3D1e8xHhvvLWsCb3aQTI96K8tvdvQyjxPcTA9npsCvUb9YzzvKAO6x3z/PG82xrun02e8E7N+uw5Dlzq7IFC7dd4YPVXZp73tBgK79WsBPVszary7RCG8kSSDvOIaTD19rCe8cWARvM7HDr2hBJ87SzljvdRI+7x8nDM9LaimO5e99Tq+H0o8M8rFvJIDorocfW+9S8m4PTOz4Tyxupo7omLZO0hpkjul6Rg87p6LPKRVsryrBO273pcLPEIJeL0GVGq9T/iNPOTxgLt8m5o8CZbuuxuZq7yWa9w7dGnuPFMTV7xx44s8sTcbvaprCr1DJDe9Z/3jO2MLSTyqpVs7AoCfvO/fm71Lovc8+N+Du4LFZzxgg9o8y539vKA1a7xPXVS9R41ePebNvTs6jRc9NQJkvO7Vo7wxQ448LMQ0PCf1G73bEP686Z8EOzgzvDwVVqE8MBmPvT9nAD2C6OY8kE2VPED9sLyvemI8BVyhPIYQ0rxhFjk8RxsEvkujij0LefO8DIIGvZjEFz2pKv28EtmaO5vg17vPDCw8UJCVO17wlzx+cc496akgPfPNSzxAUfI6j0lkPUEyhb1HK4U8YPUyPQDo4byFmms9Ick3O7UMDD26Dxm8C6YRvcRQHj0Ju8e71kx0uaUYAT2L9FA9my6dvFG3pD0pXbO86r/sPAKomzziz+Q8htdhPFvBFL3FF208cjruPCI6Mz0b3247uK+WPDqiw7y2iCK7E8w8PSdbBjw/SqS8Yja2vNDeIb0hDJq8HRXXPJYm8jzZWOa6ejTDPBGcZjp+LgS9dk77PFq/rjxLBSI8A1v0PPSeET33foa8U3OOPBtyBz0Sfhc8L5XjO24CXDvH3SA9ggEkva9hej1ekFa9ybImPCybBj19MCA7vWzwPDWSNT7Hn668CVNLPD5Kbzx8XiE9na/IvHzRLr3HED89JO8nPTE74TwulNS8yBNdO7g4r70N+yo95UIUPRcmjrz/KkK9001xva0bczr4lQK8pg/BPBtXwDyAb4g8NFPPvHb4zDwboOa8pe8BuwcPFzsgegg918mEPTejL72aZ/G7oexBvW9Ri7nY3IS86wrguxWpEb3U/gs9c3K5u7+pjjwzQAs91MIiva+z4bwSoqO7/NYbPEaEL7uXDvs7X4dNPRgh5DujMHk9VyQmPElxVT3YpCK9jUTXPJBd/bu1piu9csU4PAVaYjzDdy69+Qo9vIt9/Lz53Ti8O9WXPL+nvjzVelU8U8emupfcMDtGEJU8ac3IOxKjnr2uuK084q89Pd/jDjzB8ak8zN2DPDPnWbw8wHQ8IsOWPFMr17zYzoe8CB3oPEnJ6ju6JhW9+9JCvS7EIrohG009ydAxvftIiTyaP4o9WwW8PBtq3TsXIjC9oHUSvZeMYjsUdU89aSXvvLhKSb203WA8APXjOnd4hjx0bQQ87YCkvfWaaD3gnRO9BjpxPAws7Ty7Mo88XwHiu+h4Fj0zgvG6p/MAvfuMz7yYaAa85u8nPRxl+zrrwc48IlLlvNea9zyNv4s8nzw1u8/Cg7uqYO884XiovBmuwztQdIc8wfAtOpwW+Tx1bgg9kZx5PVt6X718YcC8pvTVu/j/5DwlorG85CTfPKRAuDyetDq9Lc4HvH/BhjwBKh885Uf7vMlOoLt8vi29gE9hvTb3Mj3t/IQ7wg3oOpHseLwK58K8XlWKvXXVSDrTUDs7ghWbPXKK8jwxD5K8F9Xeu+FbJ72nCZu8lJATvORorDrN07C8hmAmPNovBr3qnPO84xeDvDj/t72n3Qa9i1e7PNhqhr1r1J08o9MqvEwayrys+oO827k1Pdxakrx5GS28qeSwPMuguTxQmc86u9IhvEmbvzzibY07vkTfO/sdyLyS0aU8BfvOvNoCuzxFCKg8BFqdPF2qlr3adBG8W7YJPSVgO73fCWG8je66PIL6Gj1IQRk8tuZaPNjNL72EUda8Tsmbu45FAD1w/wK9R5KyPJ9SiD2TLwO8n11dPcZIijyQSdM6TSykvAvdAb25Ira8WJLYvLXkmLyQ7X+8GyBCPRhzxzw6icw8i3mmu0vIrLw3e8+8kQmxu/27mrzrbU680yisPM8mtDr/UsO8Le2KPH5GhDxoORE9OUxBvBI5ajyCE2Q8lhB0vIBSHr1Wx6U8hei4u/uYs7w6F1G97pptPEZGeLxvV9I9RLkwPMdjNT2+mLa7n0qdPLFZWL12vgo9MrrPPJUeP73M+3k9AAyyu1kQc7yTDjW9oBb8vPrwmrq8fEm9EFmcPWhB/Lua9Xy8J+EUPGkSAj2gxHq8OXTXuyJYvDwweYg8rcINPdA3ub1rrUA8EHeXPC2HADw8lnO7UXUivKI0d70iwwg85S4/PNa8czszvCW9r+15PC6B2zxzka87dlWjvKy/Dj35Z8o8RBTLPCnsnDxP9Dc8QYAOOrQYyDyrRyS8Hg6MO1/QET1lyZ86c6kyu2N/GrywPcW88hNXvO3eCTsaKiu7CIhmuFpmPLzARn89kUGOO3aH0LxH/nu8SJnMPCIPAT2vhug8Cc+aPLJHhD2DIDI98Q8rvYlFC71Xeuq8s+QBPf6wo7s/h/U8sIsoPGqU4zsoaio94cQ4uhAtY73OLsO7ZZSsvLsx8LxCsYE9+T1bvUTU7Dzgkjs9bvsHPRW58j1RCty8byykPAmdAT0U8Ig72+sIPNdq5zz8NwS8CEUoPenk87wXBDi9WYXkPEdnu7zsBNG5QEGVPbEXBT31t+G8w1yPvGvuALrwaIk8'

**Why does it not look like a vector?**

Remember from our theory primer how vector embeddings are lists with numbers? The string above doesn't look anything like it ```gte-768:9wisvV3v1D0Pb1M7CWzzPEv727stV8u9ttGePBKJNTsd...```.

The reason why this embedding does not look like a list of numbers is rather simple: **Impresso encodes embeddings internally in a data-efficient format**, as cryptic-looking strings that are given by an algorithm that maps vectors to strings, and vice versa.

Let's introduce **two helper functions**.
They allow us to apply the algorithm and map back-and-forth between vectors and data-friendly encodings:

In [9]:
# Convert our embedding string to a vector with 768 dimensions:

import base64
import struct

def string2vector(embedding_string):
    # convert base64 string to a float array
    _, arr = embedding_string.split(':')
    arr = base64.b64decode(arr)
    embedding_vector = [struct.unpack('f', arr[i:i+4])[0] for i in range(0, len(arr), 4)]
    return embedding_vector

def vector2string(vec, prefix="gte-768"):
    # pack floats into bytes
    arr = b''.join(struct.pack('f', x) for x in vec)
    # encode bytes to base64 string
    encoded = base64.b64encode(arr).decode('utf-8')
    # return in same format as original ("prefix:encoded_string")
    return f"{prefix}:{encoded}"

Let's test those string-to-embedding and embedding-to-string mappings.
First, we inspect the first five values of the embedding for our "Schumann" text.

In [10]:
string2vector(embedding)[:5]

[-0.08400146663188934,
 0.1039721742272377,
 0.003226242493838072,
 0.029714610427618027,
 -0.006713328883051872]

Seems like it worked, as the output is now a list with numbers!
Let us verify the conversion correctness; which means mapping the serialized embedding to an embedding and then back to the serialized string again.
We print *True* if the output is the same as the input:

In [11]:
# Boolean expression to verify conversion correctness:

embedding == vector2string(string2vector(embedding))

True

## Computing Similarity of Documents in Impresso

Recall from the little theory primer on top that **embeddings are powerful for comparing and searching texts**.
Let's put this to the practical example, using the Impresso API and real texts.

In [12]:
# we're defining some texts
text1 = "Schumann the politician"
text2 = "Schumann der politiker"
text3 = "Schumann the composer"

# text1 vs text2
s1 = vector_similarity(string2vector(client.tools.embed_text(text=text1, target="text")),
                       string2vector(client.tools.embed_text(text=text2, target="text")))
# text1 vs text3
s2 = vector_similarity(string2vector(client.tools.embed_text(text=text1, target="text")),
                       string2vector(client.tools.embed_text(text=text3, target="text")))

print(f"Similarity between Text \"{text1}\" and \"{text2}\": {s1}")
print(f"Similarity between Text \"{text1}\" and \"{text3}\": {s2}")

Similarity between Text "Schumann the politician" and "Schumann der politiker": 0.9331190590759458
Similarity between Text "Schumann the politician" and "Schumann the composer": 0.8527832378536088

> **Take away**: Recall that the higher the score, the more similar the two documents are. Even though text 1 and text 3 are written in the same language (English), they are less similar in the semantic vector space than text 1 and text 2, which are written in different languages (English and German) but both refer to the same Schumann. In other words, we see here indeed that **embeddings capture meaning rather than simple word overlap**.

# 3. Impresso's embedding search

In this part of the notebook, we will experiment with embedding-based retrieval for both text and image.

## Text Retrieval Across Languages

First, we embed our text, and then we retrieve the most similar documents in a dataset.
Thanks to embeddings, **search can be performed across languages and through all documents in Impresso**!
You can also embed and search based on any text that you like, even if they are not contained in Impresso.

In [13]:
# Feel free to overwrite the string in the `text` variable:

text = "Schumann the politician"
embedding = client.tools.embed_text(text=text, target="text")
client.search.find(
  embedding=embedding,
  limit=5
)

## Setting Language Restrictions

Our embeddings can retrieve all kinds of data across languages!
But this is not always what we want.
Sometimes, we want to **find texts only from a target language of our choice**.
Here's how that can be done in Impresso: Set `language` to either `fr` `de` `en` or `lb` (Luxembourgish):

In [14]:
client.search.find(
  language="fr",
  embedding=embedding,
  limit=5
)

## Image retrieval with embeddings

Suppose we have an image or a piece of text and we want to find out whether there are any images within Impresso that are similar to it. In that case, we can rely on the **Impresso image search to identify and retrieve visually or semantically related images**.

### Use-case A: We want to find similar images to our text

This is also called a "multi-modal" search, since input and retrieved data are from two different modalities (image, text).
Hence, we set the `target="multimodal"`:

In [15]:
client.images.find(
  embedding=client.tools.embed_text(text="Berlin", target="multimodal"),
  limit=3
)

### Use-case B: We want to find similar images to our image

In [16]:
client.images.find(
  embedding=client.tools.embed_image(image="https://impresso-project.ch/assets/images/posts/rep-thomas.png", target="image"),
  limit=3
)

> For more information on multimodal search and retrieval with Impresso, see the [explore_multimodal-embeddings](https://colab.research.google.com/github/impresso/impresso-datalab-notebooks/blob/impresso@bnf/workshop_resources/ws4-embeddings/explore_multimodal-embeddings.ipynb) notebook!

### Other useful functionalities

Say we found a matching article in Impresso, but **how would we get its embedding**?
Here's a one-liner to make that work.

In [17]:
# Get the embedding of a specific article by its ID:

article_id = "oeuvre-1938-02-25-a-i0003"
original_embedding = client.content_items.get_embeddings(article_id)[0]
original_embedding

'gte-768:uLaivUFj0T1XUPy8J1HaPJRUmL3in/27LMhBvSWaaz1X0ZE9RIMGvRIbHrynFjw8DOeMPNRo3T0p4TQ6NLPBPfTjWj2KPpE8akvIPe2DHr3OBG49KLogPcbMaTzafiS7GIDxvPBJ0rzcZtU9VJR2vVai170H7Yc91ZyuveGQuDyRVTw97tt0PVramz0n/pq8qkZaPTfodj2mX828hQ8XPOvCgTu93NK8dNDQvJddIrxPLyO7sqDbPEMf17zt1t08LQuYObQwtroA10A8F8TrPJbSXrtPNLo8VW1iPKyT3jzgKgG+zIu+PLFmzz3DBra8+3aEPF3eDrv049o6ZtO8vc6Q1TzqNz48ePWcO2M+y7y+w589sJEWPRe0Aj1jana7aynLughvgTvYGnU87MeYPRMlzDsUsA+8sptEPON46Tzp71C9cTvfPMqjjTzJP948pxY8O2pQ3zw9mAY9bnWrvIYZxTxLmjE8bb68OA4ifTxe6Dy8PuUKvbOaID2hCb+7+A2+vM/5mzsqxM68Y2VfPQQeijzlEvI8gOrKPB4wgTztfgc87mEhPAsJirzBe3K7i7dAvZAIOL3v0KK9h6SIu3GlSb3Rjo25uOYAvQigwz3gUZU9Z2OXvAGrFT1LmjE99UcKPJPlFjy3nhO9rtUQvVsiib0xXI88Ps7fu2Cfq71Y2788DiJ9vau+pT3D5Dg9+b+Vu0v/hL1avtk8wi3Ku1Q3ib1KoGw9z/6yPLjPVTxgeJe9hF0/PH0NbL1HcM685ubGu7AsQz2vLWe85AOtvKZtrj3S5mM9MKWgPJsYBD1xO988JGmpu9+GirybPxi9Ao4vvVgu/zzOlWw8OlG9vGQcTj2RqHs50r9PPBaTKTxITlG927T9PHiyRj2YYrk8GCOEvOo3vrwxqjc8DDrMPGINCT23o6q8wSizvI/F4TytRbY8/x/SPHPLOb1m/+e734uhvN1Jb73zHIO9aynLOiFJdD25i9s7uYvbO4/cDL0NGM86+zhFPVYk0bysHiK9t/ZpvUFjUTwzl3+7+/XuvLcNFb3k4S89t6jBPEHS0j290qQ7tVEPPTYscby46xc9oMqbvajIkztRWqq96jzVvDKIujy7PTO8wfyHPINTEbwUCOY71xBHPHR9kTxu7368bb68uzDRS7uRUCU9LXUCvZ3C9btPYGW9GchevfeZJb2jnjA8qaYWPaNyBb3RtSE8iYeiOUzL87yNsQW6eEjcPNEI4TwfjW67HMe6POh7uLuyoNu8P6fLPGmJB72hCb88klpTvK0sg73rQew7DOcMPDy6A7teO3y96V5SPOFuO71tvjw9Moi6vF7jpbwjrSM9TXi0vCfcHT3TndI81SiWvH8zXDzqNz48i4sVvUsP7rzK8bW8tuw7vDathrshz6C8RBQFPQLc171fGf88GVndvH13Vrz0kJs8b1MuPIZFcD3FdBM7cXkePflaQr3va088SyYZvSdRWr0I7ms89nhMPMO4jbznyeC8DYI5vRTXo7rJOke9H5+CPe86DT1/M9y6D/vou/iFiT2Fgy892ohSvJ3CdbwsFmo9FNcjPfWfYL0LYeC8BSi4O6B++zwoCMm89Z9gvOaYHr1cbw09PQcIPYub/rxbIgm8WLSruqwHd71EGRw9c8s5PCrEzjw2LHG88ES7vPwyir3i3Tw9ZgT/PCuAVD0voIk8UotsvcgTMzxlzqW8Fut/PVHOwjxF8gc9Hw6EuwXaD7wZWV08yTpHPOU0b7wBsCy99nhMvG7q5zwTTGA85C/YvOtTAD1wMTE9UCCePQDNErrGfsE89UcKPHFdXL0YTy+8tznAvcOcSz34DT67aDwDPDQYFTxnXgC9nbjHPBSwj7zcExY7DRjPOsuoJDxBzTs9ZrG/PZX02zw0GJU8nN9bPOLdPL1X0RE9wXtyO1m5wrwAPBQ9EoofPYRdP7uHI/O7U14dvRC3brzr6RW8hDGUvALhbjz1TKG8fimuPB7ywT15rIu8xlctPObmRjx03rE918IePNK6OL3sx5g8jTDwu0qyAD1X+CW9bRH8PICiXb2G8rC8Hfh8PAUtzzxacDG8qn8CvdyN6bzW3wQ8LxrdPB86r7xWtU+93iLbPDeLCT2zft68FmyVPDOX/zshImA79wMQPGzlUDxRxJQ89uI2PcqjDT0ufzA9umTHvDM/qTwYKBs9Y2p2vfeC+jyJIk+9FG05PajIEzwg8R27o+zYPMMxHT40s0G9WnCxPEY/DD3VKJY8y8+4OmTJDr3oVKS8EWlGPKK7ljurtVs8/4k8Pc/dWb2nFjw71TLEPPynRr1lZDu9AmIEvfgNvroGWXq75bUEPNTE5jx1YCu9GuQgPJFVvDwZ3wm9aJRZuxq9DDzf2Um6X1c+Pf5o47xDzJc8MU6uvfLZLL0MNbW95RLyvJ3CdTurtds8JGQSvYQ7wjydwvU8rHFhOt8AXryhCb+8ro0jvZ50TbzFoL48rGczPTM/qTy6gAk9YHiXPAxDlj21YXg7IwX6OywtlTzPIDC9xXQTvKwZCzyb1a28iZFQPCRkkjwP++g71xDHvDqk/LsfOq+8oCalOoiCizwdqtQ8f9sFvTX7rr0vwoa8LC2VPLbFJ7tCaGg93UTYPPMF2LxC7hQ8jJAsPV02Zb0VtSa9aR+dPMgTMz2UWS+9igBSvWiUWbq5OJw8B+nUPFJ7g7xhqdk9efqzvNPrej0NGE+9JZrrO/uAsrx+Ahq8bYB9vfTjWrx7lDw8SuPCPMMQZDouUwW95pOHvYmMuTx/M1y6qtxvvIxN1jyyTRw8NLNBPSnhtDsfNZi89baLPVNZhjyLlue8xTZUPcTCOzwM5ww7Q0ZrPIekiDysceE6D/tovDKIujzQ1568heiCPFi0q7r4Db66/LH0PDX7rjuxagK70NeePJjfm707CKy8ay7ivPv17jwiho+7UotsPU19SzyVegi90NcevQT8jDxlXyS9pjMiPBoyybzvOg298SfVvJUQHj0VHxG9D61AO54hjrySLqi8I7uEvf5BzzyYtXi8csELvO8jYj1JBUA8jrYcvYKcIr2kVR+9FS96vFsiibx94UC9MzqSPKuORzxfMCq9osCtPIYQ+7149Rw8fG0oPGXOJb3r6ZU8cTZIvAnH17xwMTG9csELPWFWmjseMIE8c/JNPCWa6zsEduA7MNHLu1OsxbzprPq7DDW1uwUouLx/4Bw94yrBPFtJnbukUAg558lgPHIPtL0rTxK9L8IGvUzL87s3kKA7YanZPDqk/Dw2LHG77MeYPDClIL3vufe8E9KMvI/+iT1POVG9f+CcvD+AtzwIAAC9cTvfPDjBYjsjsro8Rj8MvG56wrx4ZB69yvvjPInf+Dwihg+9zIs+PflaQj0sVKk83wDevIOr5zskaam872vPvFxTS7yGXBs9wSgzPUIVKTuq3O+6IUl0vLmybzxxNkg8Mo1RvHuUPDz7e5s8ketRvTYAxrzMi768AM2SunhDRTwx1mK9Hw6EvN4n8jsaoco9v2eWu/8aOzwtEK+8EM4Zvd0dRL1NeLS84/4VPYCXi7wKfsY8jbGFOxL5oDwPhqy8AbAsPKrc7zoVur07zpVsOx2lvbyECoC8CoPduom45DwRPZs8yewevJ4hjjyo7yc8NptyPVmSLr1jZd88u0fhPDzhlzwsp2i772tPvIcYIb34NFI8fMV+vBUv+ryCoTk81t+EvJ2Rs7pLlZo8jGSBvT/T9jzy1BU9u6w0vTX7LrwgZlo8AEz9u85CrTwmc1c8b1MuvJsYBD3M2WY87xiQvC7kAzzRcks95pieOmAOLb2PW3e99PoFvZ9NOT1NOnU9CG+BvK9wPb3XPPK8xsxpPDy6Az0i1Dc8JyrGPG17Zj0OoxI9V2cnvScDsjxZkq68iIKLvNZZWL0SR8k8+eYpPBT+N70JTYQ8A0CHvIepn7w73IA8teekvIOEU708S4I9/YrgvCFJdLyPW3c998A5PRe0gj0n1wY8NB2sPG7q5zxwBYY7L6AJPPgS1TzcExa8oQm/OzsILLwYgHG9CVIbPLcNFT24F0O9W3pfPUXb3DtZ9wG9vrW+u2r4iDs+9fM8'

We can also **get embeddings for any images in Impresso**.
Be ready! They also come in the quirky encoded format.

In [18]:
# Get the embedding of a specific image by its ID:

image_id = "humanite-1948-12-31-a-i0045"
embeddings = client.images.get_embeddings(image_id)
embeddings[0]

'openclip-768:ampZvAlQUz1sPq48UkkdvD7QCr3sUTi9M+EXvAMJyr3H1548OpLLvHQkl7zpSK69CRuePEljNDzJdj69AtSUvTvHADwicY88HcllPQLUVD29HWE80vvGvHQklzxVh9w8ud8hvDxmIDw7x4C8eGJWvV1txbytTPi85KCEPB4zUL04vvY8jXoIPZxQiDp1jgG9SIrIPJf/kLzA7B68wcWKvBbeZTxokW08yEEJPV7XL711WYy9HcllvVJJnTpIiki8iQeUvK6BrTx/pIi75dU5vXEbDT21MmG9fAqAvOLMr7yP/ME6l/+QvCkiwzyqDrm8sCDNOwE1tbyTV+e8nBY8PFWH3Lw7/DU97fBXvKMjubt8CoC8PgXAO3JQQr0HQjI6CRsevfDErDzqshg99DehOx9ohb0AAAC9CRuePOUKb7w7x4A98wLsPIY9bbvt8Nc8vR1hPMx/iL1TrnC8xQPKPDjzqzyTjJw95QrvvLAgzbzJcac7FHkSPNhHJ7w6kss8AAAAvTOnSzwrweI7HuG0OrL0oby2Z5a8GoYPO19Bmrzt8Ne86rIYPREBB7wj2/m8qg65vHiXCzu2Zxa8OpJLveqyGLu2Z5a8i3H+vMb5m7o/byo98KKvus5THb367Wu8ONtcuyPbeTwUIuA6cLEiPOUKbz38HQq8nBY8vMoV3jwC1FQ9IxAvvaoOubyU9ga9O8eAPCQLmLkrwWK8VYfcOz4FQLzt8Nc7s14MvUDZFL2X/5A8ATU1PU7RkTtUUic9DY6SPHEbDb048yu9DY6SvOepDj0pXA88ER4NPoBIv7xaLwa8JXoZvVg5NLtaZLu9cm0ou6hvmTwipkQ9z70HPVvOJb3Biz68F7fRvALUVD0icQ+9u0T1vAq6PTwdyWW9JXoZvcl2Pr3KFd680CfyvMUDyjxXWzG9yhXevNaohzsI5ug8yXa+vOLMr7xyUEI91zRvuxe3UbzizC+8wcWKPJNX5zyp2QM9VFInvcUDyjxh4Lm8K8FiPKBUezwC1FQ9ITyaPQM+P70+BYC9tJPBvD4FQDy536G7nBY8PFovBj0hdia7bxKDOZp3HDyR7Xw98wLsvCvB4jqLcf68AtRUPKT8pDywIE07ud+hu8UDyrw3VIw8ejYrva/rFz3lCm+8PgXAvLSTwTybPdA8zlMdvUiKyLzeWbs8Hv6avAKfn70ai6Y8+yKhvO3wV7zymAG8roGtPKt4Iz3a5ka8r+uXPaziDTy7RPW8coqOO7gGtjyTV2e8ATU1PelILr0I5mg9PGYgvaT8JLyTjBw9ejYrPVJJnTo4vvY8V1uxPNgNW7za5ka8yXa+PMbctbuVK7w8lMFRvXbDtjy2Z5Y8QX3LO60XQz1ihPC77FE4vQ74fLv5g4G848IBu5tyhbzmdBm+PgXAO+3w1zzJq3O956kOPQYSFD06kku9jxkovffMEjkJUFO9PgVAPW8Sg7xVh9w8LJpOPI16CL2zXgy9jXoIvdFcpzyZnrA8CVBTPT86db0+BUA9AAAAvUX11rp2w7Y81m47vJmeMLz3r6y7yXY+vVhzgDo3VIy8qDpkvAAAAD2PGag8rrZivX50arxdbUU9rMUnuDi+9jwxsfm7BhKUPUCk37za5sY7OpLLvDi+djwSoCY8yhXevP+VlbzQJ/I8eJcLvUCkX7zmP6S8ATW1PGcsGjzkoAS9r+uXvU563zu7fkE85nRZPXQkFz3IQQk9wypePPKYATyugS28GOyGPFuZ8Lx3+Gs9RuuoPMUDSrzQJ3I8Y7QOvAKfHz0UeRI8PgVAvVwDWz3KGvW7VcGoO+UKbzyiXQU8F7dROIZaUzyLcf684syvvJT2Bj38HQo8W86lu4xK6ruugS09ampZvB7+mr35g4G84C0QPPXWQLyuga28bxKDPMtKE7wdyeW8pptEuo6vPb0I5ug8QX3Lu36pn7w7qhq6xQPKvHhiVj29Ose5yXa+PBEBB7z3zJK5vR3hu4txfjwDCco9yXGnOyWvTr1Iisg7AwmKPJs90DxyUMI86N6DPag65Lx2w7a8ZVMuvLBVgjxhVMI+D9FovOOINTv/lRW9SIrIPD86dT22EGS7kiKyvaGEGTx/hyK7COZovaabxLy7fkE8wcWKvMhBCb3nqQ69NIC3PJaVJj1YxRs9UHAxPHJtKDuX/xC8Hv6aPHhiVj2utqK9AAAAvXiXC70jEC+9W86lvCMQL727RPU8ATW1vAMJiry0k0E9SIpIvK0XQ71Iikg8z70HPa/rF71jtA68Wi8GPLUy4TwkRWS9AtRUPR9oBb2pE9C7K/suvBEBB7tSSZ2856mOvazFJ7pdbcU8O8cAPE7REbxyM1w6REyJvNXPmzwBamo9Dvj8vEiKyDqy9KG8/B0KvGHgubwP0Wg8bxKDPHB87bzS+8a8AtRUvZOM3D2TjBy9/B0KPEljNDymm8Q8J4Oju5UrvDwHsTM97IZtPZNXZztApN883lm7PDvHgLx4lwu9Pzp1PWVTLrwFqKk8thDkugkbHrwm5IM8RfVWumpqWbxOel+79P3UuzSAt7yutqI9Ukmdu/evLLwrweI86xwDPabVkLtokW28IxAvvanZA71h4Lk8Pzp1vQBvgbsVxna+rUz4PAYSFL2wVQI9FhgyvLhAAjwe/pq9KSJDvI8ZKD0icY+95KCEvFwDW71UUic9cRsNPUDZFD15zEA9Ja9OvTxmID1Bfcs7G0zDuuAtELu0yHY9x9cePVa8kbw+0Io9mZ6wPDpdFj0+BUA9vR3hO8oV3jyPGSg8UkkdvAFqaj2k/KQ8f01WPDSANzxVh9w8k1dnvEDZFL2cFjy8zLS9vVRSJ73f+Nq8y0qTPFvOJT0ngyO8W5RZu3iXC72wIM28yEEJPaZheDyJDKu73lm7vNgNW7x1jgG9yhXevGgFhrsbEne7rOINPZf/kLzt8Nc7M6dLvDpdFj0I5ui8NIC3PI8ZqLy4BrY8Afvou+3w17yy9KE8G0xDuyWvzjw7/DU9RusovOp4zLrdtQQ8wYs+vCgs8TmYafs85QpvvJCDEj2z7wq7REwJPOY/pLySIjK92uZGPJTBkT3qshi7OPOrPK/rl71wfO086N7DPG8Sg7w+0Ao9+YOBvHhilr0HfH49m3KFvBYYMrys4o27cLGiPD4FwLxjf9k8JJf/ugAAAL3XNG87YtuiuwE1tbzA7B683lQkPFa8Eb0JGx69HcnlPKg65DyYaXu9HcllPQjm6LyjBlM7i6azvMl2vrzBiz68BaipPFvOpTxwsaK8/5UVPKkT0DtVh9w87FE4Pf+VlTzqshg9qdkDvSQLmDq9Okc5JuSDvH50ajzsUTg9y0qTPEljNLyUwVE9XW3FPJf/EDw+BUC8+yKhPKt4Iz3wv5U7AAAAPVWH3LzBiz685j+kvFBwMTywIM29K8HiuyeDIzywIE29rOINPUiKSDxaLwY9yhr1OxHHOjtwfO287Q2+Oka28zx5XT87I9t5vK0XQ72CqHu45QpvvfC/lTs6XRY9f03WO6zijT3/lRU9u0T1PKhvmbygVPs7sCBNvFovhrw7x4C8ATU1PMUDyjwz4Zc8QNmUvCRFZL2wVYI9lMFRvSJxD71UUic96rKYPDqSyzyLprM8W5TZurL0Ib1+dOo8J4MjvFa8ET1WvJG8Y7SOPMMqXrwkC5g7GxJ3O+UKbzzdtQQ8TtERPOqymLuy9CE9svQhveSgBD0hdiY77fBXPCkiQ7yz7wq76N6DvTxmID2LcX68/5UVvGO0jrzH1548W86lvH9NVjyTV2e9jxkovAcIZjsdyeU8SIpIPCWvzjwrwWI8InGPPUiKyDwicY+8kpGzu5mesDwm5IM8fnRqPMl2Pr2s4g09dy0hPe27Ir3FA0q8W86lve3wV7xIxBS8sCBNPGHguTxUUic9PgWAPQH76DvtKqQ7JXoZvR3J5TyiXYW7Tnrfu5tyhbyCqPu4lMFRveqyGLx6Nqs8rOKNu3hiVr1YxZu9QQ5KveqyGDx4l4s8IxCvPH506jy7RPU8W5TZuvsiobxblFm7Dvj8vHhi1rxGtvM8Ft5lPCPb+bxblFk7zlMdvVjFG71yUMK7'

Tired of looking at encodings and vectors?
Let's learn **how we can directly retrieve the image that's represented by the embedding**!

In [19]:
# Get a specific image and its embedding by its ID:

image_id = "humanite-1948-12-31-a-i0045"
image = client.images.get(image_id, include_embeddings=True)
image

# Conclusion

In this notebook, we explored **how Impresso’s embedding ecosystem transforms text and images into meaningful vector representations**, enabling:

- similarity search
- cross-lingual retrieval
- multimodal linking

By experimenting with simple similarity functions and the Impresso API, you have seen how embeddings reveal latent relationships beyond surface wording. These techniques provide a foundation for more advanced workflows, such as **document clustering, cross-media analysis, and building richer historical research pipelines**.

---
## Project and License info

### Notebook credits [![CreditLogo.png]()](https://credit.niso.org/)

**Writing - Original draft:**  Roman Kalyakin. **Conceptualization:** Marten Düring. **Software:** Roman Kalyakin. **Writing - Review & Editing**: Juri Opitz, Cao Vy. **Validation:** Martin Grandjean, Caio Mello. **Datalab editorial board:** Caio Mello (Managing), Cao Vy, Pauline Conti, Emanuela Boros, Marten Düring, Juri Opitz, Martin Grandjean, Estelle Bunout. **Data curation & Formal analysis:** Maud Ehrmann, Emanuela Boros, Pauline Conti, Simon Clematide, Juri Opitz, Andrianos Michail. **Methodology:** Roman Kalyakin. **Supervision:** Marten Düring. **Funding acquisition:** Maud Ehrmann, Simon Clematide, Marten Düring, Raphaëlle Ruppen Coutaz.

<br><a target="_blank" href="https://creativecommons.org/licenses/by/4.0/">
  <img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png"  width="100" alt="Open In Colab"/>
</a>

This notebook is published under [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/)

For feedback on this notebook, please send an email to info@impresso-project.ch

### Impresso project

[Impresso - Media Monitoring of the Past](https://impresso-project.ch) is an interdisciplinary research project that aims to develop and consolidate tools for processing and exploring large collections of media archives across modalities, time, languages and national borders. The first project (2017-2021) was funded by the Swiss National Science Foundation under grant No. [CRSII5_173719](http://p3.snf.ch/project-173719) and the second project (2023-2027) by the SNSF under grant No. [CRSII5_213585](https://data.snf.ch/grants/grant/213585) and the Luxembourg National Research Fund under grant No. 17498891.
<br></br>
### License

All Impresso code is published open source under the [GNU Affero General Public License](https://github.com/impresso/impresso-pyindexation/blob/master/LICENSE) v3 or later.


---

<p align="center">
  <img src="https://github.com/impresso/impresso.github.io/blob/master/assets/images/3x1--Yellow-Impresso-Black-on-White--transparent.png?raw=true" width="350" alt="Impresso Project Logo"/>
</p>